# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24ad6820cf4281dfa98746256c522efa1d5d34ebb41a412ce0481bb7518fe3df77c6dec8e13c5ff6413b44977403afd066e75e755a7a32e0d49ebc5e06802e44
  database:
    username: amir
    password: amir

test:
  secret_key_base: 0b31a311a1f83da4a7eb87d5daabcf14842192cc8cc9cd77c0f860f1aca9633a4bc7955c21228c1c917d88ef1ccbfbee36b7e7607957117fc5af537879864534
  database:
    username: amir
    password: amir
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

heroku config:add SENDGRID_USERNAME='MusinAmir'
heroku config:add SENDGRID_PASSWORD='penpen13'
heroku config:add OWNER_EMAIL='amirnaabuze@mail.ru'